name: Go CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
            go-package: ./...
  
      - name: Test
        run: go test -race -count=1 ./...
